apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole 
metadata:
   namespace: default
   name: cluster-administrator
rules:
- apiGroups: [""] # "" indicates the core API group  
  resources: ["nodes"]
  verbs: ["get", "list", "create", "delete"]